/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

public class Library {
    public boolean someLibraryMethod() {
        //throw new RuntimeException();
        return true;
    }
}
